[package]
name = "backend"
description = "Rumble client backend library"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time", "io-util"] }
quinn = { version = "0.11", default-features = false, features = ["rustls-aws-lc-rs", "bloom", "log", "platform-verifier", "runtime-tokio"] }
anyhow = "1"
bytes = "1"
api = { path = "../api" }
prost = "0.14"
rustls = { version = "0.23", default-features = true, features = [] }
webpki-roots = "1.0.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
cpal = "0.17.0"
uuid = { version = "1.19.0", features = ["v4"] }
opus = { git = "https://github.com/u6bkep/opus-rs.git", rev = "2c545dc"}
nnnoiseless = { version = "0.5.2", default-features = false }
